### ISSUE TITLE
Erro ao ativar Pugin

### ISSUE THREAD

**Issue by jtsilverio** [pagseguro/pagseguro-modulo-woocommerce#32]
Ao ativar o plugin o wordpress retorna apenas o seguinte erro:

`Parse error: syntax error, unexpected 'class' (T_CLASS), expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$' in /wp-content/plugins/woocommerce-pagseguro-oficial/classes/class-wc-pagseguro-admin.php on line 52`

**Comment by felipebranco** [comment]
@golleta Bom dia, fiz a instalação do WordPress 4.9.4, ativei os plugins do WooCommerce versão 3.3.1 e Plugin do Pagseguro  na versão 2.0.0 última versão disponível do plugin e não exibiu nenhum erro.
![wordpress_1](https://user-images.githubusercontent.com/29755801/35970513-baf0ecce-0cb1-11e8-8a95-a091e5784078.png)
![wordpress_2](https://user-images.githubusercontent.com/29755801/35970514-bb2fc962-0cb1-11e8-9884-a8b37c895c47.png)
Qual versão do plugin está usando ? Qualquer duvida pode retornar a mensagem !

**Comment by golleta** [comment]
As versoes que estou usando são:

wordpress 9.4.9
woo commerce 3.3.1
PagSeguro 2.0

**Comment by s2it-moscou** [comment]
@golleta  Bom dia, fiz a instalação do WordPress 4.9.4, ativei os plugins do WooCommerce versão 3.3.1 e Plugin do Pagseguro na versão 2.0.0 que são as última versões disponíveis de Wordpress, Woocommerce e do Plugin Pagseguro disponibilizados e não exibiu erro. Você tem o print da tela com o erro, pois não consegui reproduzir o erro.

**Comment by golleta** [comment]
Esse é o erro que estou tendo:

[](url)
<img width="1161" alt="screenshot 2018-02-16 15 32 59" src="https://user-images.githubusercontent.com/1624305/36320835-c3df7f02-132e-11e8-9e56-c5a8b272cd62.png">

**Comment by golleta** [comment]
Inclusive, desativei todos os outros plugins para ver se não era alguma incompatibilidade entre os plugins e ainda continuo tendo o mesmo erro.

**Comment by zarnitz** [comment]
Bom dia.
Estou tendo um problema semelhante.
Ao ativar o plugin está causando erro em meu site: HTTP ERROR 500
Já verifiquei permissões das pastas e até deixei tudo 777, não resolveu.

**Comment by marcossantiago** [comment]
@s2it-moscou Exato mesmo erro do golleta. 

`PHP Parse error:  syntax error, unexpected 'class' (T_CLASS), expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$' in /var/www/clients/client7/web54/wp/wp-content/plugins/pagseguro-woocommerce-git/classes/class-wc-pagseguro-admin.php on line 52, referer: http://xxxxx/wp-admin/update.php?action=upload-plugin`

Woocommerce: Versão 3.3.3
WordPress: 4.9.4
PagSeguro 2.0
PHP: 5.4.45

**Comment by marcossantiago** [comment]
Resolvi o problema atualizando o PHP para 5.6.30 !

**Comment by s2it-moscou** [comment]
@golleta e @zarnitz Estão usando qual versão do PHP! Conforme relatado acima, fiz a simulação na versão 5.6.31 e não exibiu erros ! Ao passar a versão do seu PHP consigo simular com mais precisão !

**Comment by golleta** [comment]
Estou usando a versão 5.4.452.0 como o @marcossantiago.
