### ISSUE TITLE
Exigencia de TLS 1.2 a partir de 30/06/2018

### ISSUE THREAD

**Issue by GricelRio** [pagseguro/pagseguro-modulo-woocommerce#37]
Olá, 

Alguém pode ajudar com esta exigência do PagSeguro?

A loja está no seguinte ambiente:
Wordpress: 4.8.6
Woocommerce 3.2.5
Woocommerce PagSeguro 2.12.5

Fiz um teste utilizando o plugin TLS 1.2 Test e o resultado foi este.
![image](https://user-images.githubusercontent.com/13592553/40556480-2ccbabee-6023-11e8-9008-2e26a172da88.png)

Isso significa que a exigência do PagSeguro está atendida ou é preciso verificar outros itens? 
O site da loja está hospedado na Locaweb e não tem SSL, queremos colocar, haveria alguma incompatibilidade?

Agradeço a ajuda, 
Gricel

**Comment by andredalmolin** [comment]
Todo e-commerce deve estar sob SSL.
